
name: Spring Boot CI/CD on EC2

# 워크 플로우 실행 조건 설정
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 작업
jobs:
  build:

    # 작업 환경
    runs-on: ubuntu-latest
    permissions:
      contents: read  # 코드 읽기 권한만 부여

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: application.yml 생성 후 secret 값 복붙
      run: |  # 보안 설정된 application.yml 파일 생성
        mkdir -p ./src/main/resources
        touch ./src/main/resources/application.yml
        echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
        cat ./src/main/resources/application.yml

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: memo-study
        path: build/libs/memo-study-0.0.1-SNAPSHOT.jar

  # EC2 서버로 배포 작업 정의
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: memo-study
          path: build/libs/

      # EC2에 배포
      - name: Deploy to EC2
        run: |
          # EC2 접근을 위한 SSH 개인 키 저장 및 권한 설정
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
          # EC2로 JAR 파일 복사
          scp -i private_key.pem -o StrictHostKeyChecking=no build/libs/memo-study-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/memo-study.jar
          
          # EC2에서 기존 Java 프로세스 종료 후 새 애플리케이션 실행
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "pgrep java | xargs kill -9; nohup java -jar /home/${{ secrets.EC2_USERNAME }}/memo-study.jar > app.log 2>&1 &"
          
          # 보안상 개인 키 삭제
          rm -f private_key.pem



  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'


    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
